version: "3.9"

services:
  app_node:
    container_name: app_node
    build: 
      context: ./node
    ports: 
      - "3000:3000"
    networks:
      - proxychallenge
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    container_name: nginx_serve
    build: 
      context: ./nginx
    ports:
      - 80:80
    networks:
      - proxychallenge
  mysql:
    container_name: db_mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fullcycle
      MYSQL_DATABASE: fullcycle
      MYSQL_USER: fullcycle
      MYSQL_PASSWORD: fullcycle
    networks:
      - proxychallenge
    healthcheck:
      test: ["CMD", "mysqladmin", "-u $MYSQL_USER", "-p $MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint:/docker-entrypoint-initdb.d

networks:
  proxychallenge:
    driver: bridge
